name: setup_wrf
channels:
  - conda-forge
  - defaults
dependencies:
  - hdf5=1.14.3
  - mpich=4.2.1
  - netcdf-fortran=4.6.1
  - gfortran=10.4
  - jasper=1.900.1
  - wgrib2=2.0.5
  - nco=5.3.3
  - python=3.11
